### PR TITLE
Add Internal Event Queue Support for Simulation and CPP Code Generato…

### PR DESCRIPTION
**Pull request by ankurtibrewal**
…r (C++11)

### CODE REVIEW

**Comment by terfloth** [comment]
@ankurtibrewal - Thank you very much for the contribution. We will take a closer look at it. As you may also have noticed it breaks some of unit tests. So we'll come back to you regarding this topic. Please be aware that we won't apply the pull request before our next 2.6 release end of march.

**Comment by terfloth** [comment]
@ankurtibrewal : please confirm that you agree to provide your contribution under the terms of the Eclipse Public Licence v1.0 (EPL): https://www.eclipse.org/legal/epl-v10.html

**Comment by ankurtibrewal** [comment]
Hi,

I agree to provide my contribution under the terms of Eclipse Public
License v1.0 (EPL) : https://www.eclipse.org/legal/epl-v10.html

Thanks
Ankur Tibrewal

**Comment by BeckmaR** [comment]
I merged this PR into branch [PR_509_EventQueue](/Yakindu/statecharts/tree/PR_509_EventQueue), instead of directly into master. Closing this.

**Pull request closed without merging**
