### PR TITLE
Initial commit of C# Generator for Yakindu SCR

### PR DESCRIPTION
**Pull request by m-sonntag**
Based on the Java codegen classes I created a version for C#. The examples haven't been ported yet but I was able to get it to work flawlessly with a rather complex state chart including a TimerService.

### CODE REVIEW

**Comment by andreasmuelder** [comment]
Thanks for contributing! We have a lot of test cases specified in a language called SCTUnit:
https://github.com/Yakindu/statecharts/tree/master/test-plugins/org.yakindu.sct.test.models/tests
I will add a C# code Generator for SCTUnit to generate all the unit tests for your generator and check if its working correct.

**Comment by terfloth** [comment]
@m-sonntag : Please confirm that you agree to provide your contribution under the terms of the Eclipse Public Licence v1.0 (EPL): https://www.eclipse.org/legal/epl-v10.html

**Comment by m-sonntag** [comment]
I do agree to provide the code under the EPL.

**Comment by andreasmuelder** [comment]
@terfloth We should merge this PR to the master and provide an optional BETA feature for the Csharp code generator until we have the time to implement the test code generator.

**Comment by terfloth** [comment]
@andreasmuelder I'm careful about including this even as a beta feature so closely to the 2.6 release. I prefer merging it directly after the 2.6 release is done.

**Comment by andreasmuelder** [comment]
Merging this to master

**Pull request merged**
