### PR TITLE
WIP: Documentation of execution semantics (issue #1561)

### LINKED ISSUE #1561: [Documentation] Write a new section on execution semantics

### PR DESCRIPTION
**Pull request by RainerKlute**
Resolves #1561

### CODE REVIEW

**Comment by andreasmuelder** [comment]
@RainerKlute @terfloth what is the state of this?

**Comment by andreasmuelder** [comment]
@RainerKlute @terfloth Can this be merged?

**Comment by RainerKlute** [comment]
> @RainerKlute @terfloth Can this be merged?

No, it can't. Otherwise it would not have been marked "WIP".

**Comment by andreasmuelder** [comment]
closing as orphaned, please reopen if work continues

**Pull request closed without merging**
